### ISSUE TITLE
Criar link table de forma declarativa usando `relationships.toml`

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/spreadmart#14]
Atualmente inserir uma nova base de dados na link table demanda diversas alterações manuais no script [scripts/transform.R](https://github.com/splor-mg/spreadmart/blob/main/scripts/transform.R).

Faz sentido otimizarmos essa operação focando em:

- otimizar inclusão das variáveis contendo indicadores fiscais do pacote `relatorios` nas bases;
- mover declaração dos componentes da link table para um arquivo de configuração

**Comment by fjuniorr** [comment]
Esboço inicial para a declaração da link table em um arquivo de configuração `relationships.toml`

```toml
[keys] 

"chave_rec" = ["ANO", "UO_COD", "FONTE_COD", "MDE"]
"chave_desp" = ["ANO", "UO_COD", "FUNCAO_COD", "ACAO_COD", "GRUPO_COD", "FONTE_COD", "IPU_COD", "MDE"]

[packages.reest]

"reest_rec" = "chave_rec"
"reest_desp" = "chave_desp"

[packages.sisor]

"base_orcam_receita_fiscal" = "chave_rec"
"base_qdd_fiscal" = "chave_desp"
"base_orcam_despesa_item_fiscal" = "chave_desp"
```
